env:
  es6: true
  node: true
  browser: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2016
  sourceType: module
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - double
  semi:
    - error
    - always
